apiVersion: v1
kind: Secret
metadata:
  name: artemis-broker-credentials-secret
  namespace: activemq-artemis-operator
type: Opaque
stringData:
  AMQ_USER: admin
  AMQ_PASSWORD: "MySecurePassword123!"
  AMQ_CLUSTER_USER: cluster_user
  AMQ_CLUSTER_PASSWORD: "ClusterPassword456!"