apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
  namespace: activemq-artemis-operator
spec:
  deploymentPlan:
    size: 1
    persistenceEnabled: true
    journalType: nio
    storage:
      size: 2Gi