apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
  namespace: activemq-artemis-operator
spec:
  deploymentPlan:
    size: 2
    persistenceEnabled: false
    messageMigration: true
    journalType: NIO


# docker pull quay.io/arkmq-org/activemq-artemis-broker-kubernetes

# apiVersion: broker.amq.io/v1beta1
# kind: ActiveMQArtemis
# metadata:
#   name: artemis-broker
#   namespace: activemq-artemis-operator
# spec:
#   deploymentPlan:
#     size: 2
#     # Disable persistence to get it working first
#     persistenceEnabled: false
#     # messageMigration: true
#   acceptors:
#     - name: amqp
#       protocols: amqp
#       port: 5672
#     - name: all
#       protocols: all
#       port: 61616
#   console:
#     expose: true



# apiVersion: broker.amq.io/v1beta1
# kind: ActiveMQArtemis
# metadata:
#   name: artemis-broker
# spec:
#   deploymentPlan:
#     size: 2
#     persistenceEnabled: true
#     # messageMigration requires 2+ brokers
#     messageMigration: true
