apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
  namespace: activemq-artemis-operator
spec:
  deploymentPlan:
    size: 2
    image: quay.io/artemiscloud/activemq-artemis-broker-kubernetes:1.0.25
    # Disable persistence to get it working first
    persistenceEnabled: false
  acceptors:
    - name: amqp
      protocols: amqp
      port: 5672
    - name: all
      protocols: all
      port: 61616
  console:
    expose: true