apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
  namespace: activemq-artemis-operator
spec:
  console:
    expose: true
    
  deploymentPlan:
    size: 2
    persistenceEnabled: true
    messageMigration: true
    storage:
      size: 2Gi
      storageClassName: standard
  
  # Enable Web Console  ( If we have these broker pods are nog being created nothing is shown up ,never no what's going worng )
  # console:  
  #   expose: true 
  #   exposeMode: NodePort
  
  # Configure Acceptors - OpenWire, AMQP, and STOMP
  # acceptors:
  #   - name: openWire
  #     protocols: CORE
  #     port: 61616
  #   - name: amqp
  #     protocols: AMQP
  #     port: 5672
  #   - name: stomp
  #     protocols: STOMP
  #     port: 61613
  #   - name: all
  #     protocols: ALL
  #     port: 61614

  enableMetricsPlugin: true
  
  # Environment variables
  env:
    - name: AMQ_DATA_DIR
      value: "/home/jboss/amq-broker/data"



# docker pull quay.io/arkmq-org/activemq-artemis-broker-kubernetes

# apiVersion: broker.amq.io/v1beta1
# kind: ActiveMQArtemis
# metadata:
#   name: artemis-broker
#   namespace: activemq-artemis-operator
# spec:
#   deploymentPlan:
#     size: 2
#     # Disable persistence to get it working first
#     persistenceEnabled: false
#     # messageMigration: true
#   acceptors:
#     - name: amqp
#       protocols: amqp
#       port: 5672
#     - name: all
#       protocols: all
#       port: 61616
#   console:
#     expose: true



# apiVersion: broker.amq.io/v1beta1
# kind: ActiveMQArtemis
# metadata:
#   name: artemis-broker
# spec:
#   deploymentPlan:
#     size: 2
#     persistenceEnabled: true
#     # messageMigration requires 2+ brokers
#     messageMigration: true
