apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
spec:
  deploymentPlan:
    size: 1 
    # persistenceEnabled: true
    # messageMigration requires 2+ brokers
    # messageMigration: true  