apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: activemq-artemis-operator

resources:
  - ../../base/activemq-ha/
  - broker-cr.yaml             # Broker custom resource with STOMP, console, and acceptors
  - broker-secrets.yaml        # Broker secrets for users and passwords
  - console-nodeport.yaml   # NodePort service for web console exposure




# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
# resources:
#   - https://raw.githubusercontent.com/artemiscloud/activemq-artemis-operator/v1.2.7/deploy/crds/broker_activemqartemis_crd.yaml
#   - https://raw.githubusercontent.com/artemiscloud/activemq-artemis-operator/v1.2.7/deploy/operator.yaml
#   - broker-cr.yaml   # your CR which relies on the CRD above